# Generated by Django 5.0.7 on 2024-07-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Cookies',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('lat', models.CharField(max_length=255, verbose_name='Широта')),
                ('long', models.CharField(max_length=255, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='main.cookie')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
            },
        ),
    ]
